# Generated by Django 5.0.6 on 2024-07-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='place',
            new_name='designation',
        ),
    ]
